services:
  - type: web
    name: kmercart-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: pnpm install --frozen-lockfile && pnpm remove bcrypt && pnpm add bcrypt@5.1.1 && pnpm run build
    startCommand: node --max-old-space-size=400 dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
